# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/tableWidget1.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WorkingField(object):
    def setupUi(self, WorkingField):
        WorkingField.setObjectName("WorkingField")
        WorkingField.resize(1280, 690)
        WorkingField.setMouseTracking(True)
        WorkingField.setFocusPolicy(QtCore.Qt.NoFocus)
        self.gridLayout = QtWidgets.QGridLayout(WorkingField)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_7.setSpacing(10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtWidgets.QLabel(WorkingField)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.label_15 = QtWidgets.QLabel(WorkingField)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(18)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_7.addWidget(self.label_15)
        self.label_total_term = QtWidgets.QLabel(WorkingField)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_total_term.setFont(font)
        self.label_total_term.setObjectName("label_total_term")
        self.horizontalLayout_7.addWidget(self.label_total_term)
        self.label_10 = QtWidgets.QLabel(WorkingField)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(18)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.btn_add_term = QtWidgets.QPushButton(WorkingField)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.btn_add_term.setFont(font)
        self.btn_add_term.setObjectName("btn_add_term")
        self.horizontalLayout_7.addWidget(self.btn_add_term)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.unspecified_tabWidget = QtWidgets.QTabWidget(WorkingField)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(24)
        self.unspecified_tabWidget.setFont(font)
        self.unspecified_tabWidget.setStyleSheet("")
        self.unspecified_tabWidget.setObjectName("unspecified_tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tableWidget_internal = InternalTable(self.tab)
        self.tableWidget_internal.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tableWidget_internal.setAutoFillBackground(True)
        self.tableWidget_internal.setStyleSheet("QHeaderView::section{\n"
"    background-color    : rgb(106, 154, 62);\n"
"    color: white;\n"
"}\n"
"\n"
"QTableWidget{\n"
"    background:rgb(255, 255, 255);\n"
"    alternate-background-color:rgb(224, 238, 210);\n"
"    selection-background-color:transparent;\n"
"    show-decoration-selected:10;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: rgb(37, 114, 71);\n"
"    color: white;\n"
"}")
        self.tableWidget_internal.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableWidget_internal.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_internal.setDragDropOverwriteMode(False)
        self.tableWidget_internal.setAlternatingRowColors(True)
        self.tableWidget_internal.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_internal.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_internal.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableWidget_internal.setGridStyle(QtCore.Qt.DashLine)
        self.tableWidget_internal.setWordWrap(True)
        self.tableWidget_internal.setCornerButtonEnabled(False)
        self.tableWidget_internal.setRowCount(4)
        self.tableWidget_internal.setColumnCount(11)
        self.tableWidget_internal.setObjectName("tableWidget_internal")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_internal.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_internal.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_internal.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_internal.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_internal.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_internal.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_internal.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_internal.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_internal.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_internal.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_internal.setHorizontalHeaderItem(10, item)
        self.tableWidget_internal.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_internal.horizontalHeader().setHighlightSections(False)
        self.tableWidget_internal.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget_internal.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_internal.verticalHeader().setHighlightSections(False)
        self.horizontalLayout_5.addWidget(self.tableWidget_internal)
        self.unspecified_tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tableWidget_external = ExternalTable(self.tab_2)
        self.tableWidget_external.setStyleSheet("QHeaderView::section{\n"
"    background-color    : rgb(57, 135, 144);\n"
"    color: white;\n"
"}\n"
"\n"
"QTableWidget{\n"
"    background:rgb(255, 255, 255);\n"
"    alternate-background-color:rgb(209, 235, 238);\n"
"    selection-background-color:transparent;\n"
"    show-decoration-selected:10;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: rgb(99, 186, 194);\n"
"    color: white;\n"
"}")
        self.tableWidget_external.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableWidget_external.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_external.setAlternatingRowColors(True)
        self.tableWidget_external.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_external.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_external.setGridStyle(QtCore.Qt.DashLine)
        self.tableWidget_external.setObjectName("tableWidget_external")
        self.tableWidget_external.setColumnCount(23)
        self.tableWidget_external.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_external.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_external.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_external.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_external.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_external.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_external.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_external.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_external.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_external.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_external.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_external.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_external.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_external.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_external.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_external.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_external.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_external.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_external.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_external.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_external.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_external.setHorizontalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_external.setHorizontalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_external.setHorizontalHeaderItem(22, item)
        self.tableWidget_external.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_external.horizontalHeader().setHighlightSections(False)
        self.tableWidget_external.verticalHeader().setHighlightSections(False)
        self.horizontalLayout_4.addWidget(self.tableWidget_external)
        self.unspecified_tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_4.addWidget(self.unspecified_tabWidget)
        self.teacherInfoEdit = QtWidgets.QTextEdit(WorkingField)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.teacherInfoEdit.setFont(font)
        self.teacherInfoEdit.setReadOnly(True)
        self.teacherInfoEdit.setObjectName("teacherInfoEdit")
        self.verticalLayout_4.addWidget(self.teacherInfoEdit)
        self.verticalLayout_4.setStretch(0, 5)
        self.verticalLayout_4.setStretch(1, 2)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 4, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_add = QtWidgets.QPushButton(WorkingField)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_add.sizePolicy().hasHeightForWidth())
        self.btn_add.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_add.setFont(font)
        self.btn_add.setAutoFillBackground(False)
        self.btn_add.setDefault(False)
        self.btn_add.setFlat(False)
        self.btn_add.setObjectName("btn_add")
        self.verticalLayout_2.addWidget(self.btn_add)
        self.btn_del = QtWidgets.QPushButton(WorkingField)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_del.sizePolicy().hasHeightForWidth())
        self.btn_del.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_del.setFont(font)
        self.btn_del.setObjectName("btn_del")
        self.verticalLayout_2.addWidget(self.btn_del)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 3, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(5, -1, 5, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_8 = QtWidgets.QLabel(WorkingField)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.label_school_name = QtWidgets.QLabel(WorkingField)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_school_name.setFont(font)
        self.label_school_name.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_school_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_school_name.setIndent(10)
        self.label_school_name.setObjectName("label_school_name")
        self.horizontalLayout_2.addWidget(self.label_school_name)
        self.label_12 = QtWidgets.QLabel(WorkingField)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_2.addWidget(self.label_12)
        self.label_state = QtWidgets.QLabel(WorkingField)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_state.setFont(font)
        self.label_state.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_state.setObjectName("label_state")
        self.horizontalLayout_2.addWidget(self.label_state)
        self.label_13 = QtWidgets.QLabel(WorkingField)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_2.addWidget(self.label_13)
        self.horizontalLayout_2.setStretch(1, 3)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 3, 1, 2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.schoolListWidget = QtWidgets.QListWidget(WorkingField)
        font = QtGui.QFont()
        font.setFamily("Nanum Gothic")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.schoolListWidget.setFont(font)
        self.schoolListWidget.setStyleSheet("QListWidget{\n"
"    border: 0px;\n"
"    background-color: rgb(246, 246, 246);\n"
"    selection-color: rgb(0, 0, 0);\n"
"     selection-background-color: rgb(220, 220, 220);\n"
"    font: 18pt \"Nanum Gothic\";\n"
"}\n"
"QListWidget:item{\n"
"    font: 18pt \"맑은 고딕\";\n"
"}")
        self.schoolListWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.schoolListWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.schoolListWidget.setAlternatingRowColors(True)
        self.schoolListWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.schoolListWidget.setResizeMode(QtWidgets.QListView.Adjust)
        self.schoolListWidget.setObjectName("schoolListWidget")
        self.verticalLayout_5.addWidget(self.schoolListWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(WorkingField)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.label_total_state = QtWidgets.QLabel(WorkingField)
        self.label_total_state.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_total_state.setObjectName("label_total_state")
        self.horizontalLayout_3.addWidget(self.label_total_state)
        self.label_3 = QtWidgets.QLabel(WorkingField)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_5, 1, 2, 2, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(30, 5, 5, 0)
        self.horizontalLayout_9.setSpacing(10)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_4 = QtWidgets.QLabel(WorkingField)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_9.addWidget(self.label_4)
        self.label_inside = QtWidgets.QLabel(WorkingField)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_inside.sizePolicy().hasHeightForWidth())
        self.label_inside.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_inside.setFont(font)
        self.label_inside.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_inside.setWordWrap(False)
        self.label_inside.setObjectName("label_inside")
        self.horizontalLayout_9.addWidget(self.label_inside)
        self.label_5 = QtWidgets.QLabel(WorkingField)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.label_2 = QtWidgets.QLabel(WorkingField)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_9.addWidget(self.label_2)
        self.label_outside = QtWidgets.QLabel(WorkingField)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_outside.sizePolicy().hasHeightForWidth())
        self.label_outside.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_outside.setFont(font)
        self.label_outside.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_outside.setObjectName("label_outside")
        self.horizontalLayout_9.addWidget(self.label_outside)
        self.label_6 = QtWidgets.QLabel(WorkingField)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.label_9 = QtWidgets.QLabel(WorkingField)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.label_term = QtWidgets.QLabel(WorkingField)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_term.sizePolicy().hasHeightForWidth())
        self.label_term.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_term.setFont(font)
        self.label_term.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_term.setObjectName("label_term")
        self.horizontalLayout_9.addWidget(self.label_term)
        self.label_11 = QtWidgets.QLabel(WorkingField)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_9.addWidget(self.label_11)
        self.gridLayout.addLayout(self.horizontalLayout_9, 1, 3, 1, 2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(10, -1, 10, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(WorkingField)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.verticalLayout.addWidget(self.stackedWidget)
        self.gridLayout.addLayout(self.verticalLayout, 2, 4, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.button_exit = QtWidgets.QPushButton(WorkingField)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_exit.sizePolicy().hasHeightForWidth())
        self.button_exit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.button_exit.setFont(font)
        self.button_exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_exit.setObjectName("button_exit")
        self.horizontalLayout_6.addWidget(self.button_exit)
        self.button_update = QtWidgets.QPushButton(WorkingField)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_update.sizePolicy().hasHeightForWidth())
        self.button_update.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.button_update.setFont(font)
        self.button_update.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_update.setObjectName("button_update")
        self.horizontalLayout_6.addWidget(self.button_update)
        self.button_save_result = QtWidgets.QPushButton(WorkingField)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_save_result.sizePolicy().hasHeightForWidth())
        self.button_save_result.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.button_save_result.setFont(font)
        self.button_save_result.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_save_result.setObjectName("button_save_result")
        self.horizontalLayout_6.addWidget(self.button_save_result)
        self.gridLayout.addLayout(self.horizontalLayout_6, 3, 2, 1, 3)

        self.retranslateUi(WorkingField)
        self.unspecified_tabWidget.setCurrentIndex(1)
        self.btn_add.clicked.connect(WorkingField.add)
        self.btn_del.clicked.connect(WorkingField.delete)
        self.button_update.clicked.connect(WorkingField.update_file)
        self.button_save_result.clicked.connect(WorkingField.save)
        self.button_exit.clicked.connect(WorkingField.show_dialog_exit)
        self.unspecified_tabWidget.currentChanged['int'].connect(self.tableWidget_internal.clearSelection)
        self.unspecified_tabWidget.currentChanged['int'].connect(self.tableWidget_external.clearSelection)
        self.unspecified_tabWidget.currentChanged['int'].connect(self.teacherInfoEdit.clear)
        self.tableWidget_external.currentCellChanged['int','int','int','int'].connect(WorkingField.teacherInfoChanged)
        self.tableWidget_internal.currentCellChanged['int','int','int','int'].connect(WorkingField.teacherInfoChanged)
        self.btn_add_term.clicked.connect(WorkingField.add_temp)
        self.schoolListWidget.currentRowChanged['int'].connect(WorkingField.tabChanged)
        self.schoolListWidget.currentRowChanged['int'].connect(self.stackedWidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(WorkingField)

    def retranslateUi(self, WorkingField):
        _translate = QtCore.QCoreApplication.translate
        WorkingField.setWindowTitle(_translate("WorkingField", "배치"))
        self.label.setText(_translate("WorkingField", "미지정 교사"))
        self.label_15.setText(_translate("WorkingField", "총 미충원 수 :"))
        self.label_total_term.setText(_translate("WorkingField", "0"))
        self.label_10.setText(_translate("WorkingField", "명"))
        self.btn_add_term.setText(_translate("WorkingField", "미충원 추가"))
        self.tableWidget_internal.setSortingEnabled(True)
        item = self.tableWidget_internal.horizontalHeaderItem(0)
        item.setText(_translate("WorkingField", "전보유형"))
        item = self.tableWidget_internal.horizontalHeaderItem(1)
        item.setText(_translate("WorkingField", "소속"))
        item = self.tableWidget_internal.horizontalHeaderItem(2)
        item.setText(_translate("WorkingField", "성명"))
        item = self.tableWidget_internal.horizontalHeaderItem(3)
        item.setText(_translate("WorkingField", "성별"))
        item = self.tableWidget_internal.horizontalHeaderItem(4)
        item.setText(_translate("WorkingField", "급지"))
        item = self.tableWidget_internal.horizontalHeaderItem(5)
        item.setText(_translate("WorkingField", "전보년수"))
        item = self.tableWidget_internal.horizontalHeaderItem(6)
        item.setText(_translate("WorkingField", "전보점수"))
        item = self.tableWidget_internal.horizontalHeaderItem(7)
        item.setText(_translate("WorkingField", "1지망"))
        item = self.tableWidget_internal.horizontalHeaderItem(8)
        item.setText(_translate("WorkingField", "2지망"))
        item = self.tableWidget_internal.horizontalHeaderItem(9)
        item.setText(_translate("WorkingField", "3지망"))
        item = self.tableWidget_internal.horizontalHeaderItem(10)
        item.setText(_translate("WorkingField", "비고"))
        self.unspecified_tabWidget.setTabText(self.unspecified_tabWidget.indexOf(self.tab), _translate("WorkingField", "관내"))
        self.tableWidget_external.setSortingEnabled(True)
        item = self.tableWidget_external.horizontalHeaderItem(0)
        item.setText(_translate("WorkingField", "전보유형"))
        item = self.tableWidget_external.horizontalHeaderItem(1)
        item.setText(_translate("WorkingField", "지역"))
        item = self.tableWidget_external.horizontalHeaderItem(2)
        item.setText(_translate("WorkingField", "학교명"))
        item = self.tableWidget_external.horizontalHeaderItem(3)
        item.setText(_translate("WorkingField", "직위"))
        item = self.tableWidget_external.horizontalHeaderItem(4)
        item.setText(_translate("WorkingField", "성명"))
        item = self.tableWidget_external.horizontalHeaderItem(5)
        item.setText(_translate("WorkingField", "생년월일"))
        item = self.tableWidget_external.horizontalHeaderItem(6)
        item.setText(_translate("WorkingField", "성별"))
        item = self.tableWidget_external.horizontalHeaderItem(7)
        item.setText(_translate("WorkingField", "교육총경력"))
        item = self.tableWidget_external.horizontalHeaderItem(8)
        item.setText(_translate("WorkingField", "심화전공"))
        item = self.tableWidget_external.horizontalHeaderItem(9)
        item.setText(_translate("WorkingField", "1희망지구"))
        item = self.tableWidget_external.horizontalHeaderItem(10)
        item.setText(_translate("WorkingField", "2희망지구"))
        item = self.tableWidget_external.horizontalHeaderItem(11)
        item.setText(_translate("WorkingField", "3희망지구"))
        item = self.tableWidget_external.horizontalHeaderItem(12)
        item.setText(_translate("WorkingField", "휴직종류"))
        item = self.tableWidget_external.horizontalHeaderItem(13)
        item.setText(_translate("WorkingField", "휴직시작일"))
        item = self.tableWidget_external.horizontalHeaderItem(14)
        item.setText(_translate("WorkingField", "휴직종료일"))
        item = self.tableWidget_external.horizontalHeaderItem(15)
        item.setText(_translate("WorkingField", "친인척학교명"))
        item = self.tableWidget_external.horizontalHeaderItem(16)
        item.setText(_translate("WorkingField", "관계"))
        item = self.tableWidget_external.horizontalHeaderItem(17)
        item.setText(_translate("WorkingField", "성명"))
        item = self.tableWidget_external.horizontalHeaderItem(18)
        item.setText(_translate("WorkingField", "주소"))
        item = self.tableWidget_external.horizontalHeaderItem(19)
        item.setText(_translate("WorkingField", "휴대폰"))
        item = self.tableWidget_external.horizontalHeaderItem(20)
        item.setText(_translate("WorkingField", "이메일"))
        item = self.tableWidget_external.horizontalHeaderItem(21)
        item.setText(_translate("WorkingField", "교통수단"))
        item = self.tableWidget_external.horizontalHeaderItem(22)
        item.setText(_translate("WorkingField", "비고"))
        self.unspecified_tabWidget.setTabText(self.unspecified_tabWidget.indexOf(self.tab_2), _translate("WorkingField", "관외"))
        self.btn_add.setText(_translate("WorkingField", "추가>>"))
        self.btn_del.setText(_translate("WorkingField", "<<삭제"))
        self.label_8.setText(_translate("WorkingField", "학교명"))
        self.label_school_name.setText(_translate("WorkingField", "시흥장현초"))
        self.label_12.setText(_translate("WorkingField", "결원 : "))
        self.label_state.setText(_translate("WorkingField", "0"))
        self.label_13.setText(_translate("WorkingField", "명"))
        self.label_7.setText(_translate("WorkingField", "총 결원:"))
        self.label_total_state.setText(_translate("WorkingField", "0"))
        self.label_3.setText(_translate("WorkingField", "명"))
        self.label_4.setText(_translate("WorkingField", "관내 전보 :"))
        self.label_inside.setText(_translate("WorkingField", "0"))
        self.label_5.setText(_translate("WorkingField", "명"))
        self.label_2.setText(_translate("WorkingField", "관외 전보 :"))
        self.label_outside.setText(_translate("WorkingField", "0"))
        self.label_6.setText(_translate("WorkingField", "명"))
        self.label_9.setText(_translate("WorkingField", "미충원 :"))
        self.label_term.setText(_translate("WorkingField", "0"))
        self.label_11.setText(_translate("WorkingField", "명"))
        self.button_exit.setText(_translate("WorkingField", "종료"))
        self.button_update.setText(_translate("WorkingField", "저장\n"
"(순위명부, 결충원)"))
        self.button_save_result.setText(_translate("WorkingField", "저장\n"
"(배정결과)"))
from table_external import ExternalTable
from table_internal import InternalTable
